server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-44-206-89-185.compute-1.amazonaws.com/dcdc6upd7siivr
    username: qdyfryiiykfftq
    password: 45aa7f77e5aa8c7c84c8b4db11bc6692a4dbab4b1152d92a6683de7a5c688b63
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect