server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-44-206-11-200.compute-1.amazonaws.com:5432/d1lvhdlu2d4sv3
    username: oukmtaqpinaijw
    password: c00051ece20ea92695163d21d7b1ff7276b455ea36af7971bb14729cebbc38b2
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect